/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./src/app/layouts/auth-layout.vue')['default']
    Button: typeof import('primevue/button')['default']
    Divider: typeof import('primevue/divider')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    MainCtaBanner: typeof import('./src/app/components/main/MainCtaBanner.vue')['default']
    MainFooter: typeof import('./src/app/components/main/MainFooter.vue')['default']
    MainHeader: typeof import('./src/app/components/main/MainHeader.vue')['default']
    MainLayout: typeof import('./src/app/layouts/main-layout.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VDarkModeToggler: typeof import('./src/app/components/ui/VDarkModeToggler.vue')['default']
    VErrorMessage: typeof import('./src/app/components/ui/VErrorMessage.vue')['default']
    VShapes: typeof import('./src/app/components/ui/VShapes.vue')['default']
    VueLayout: typeof import('./src/app/layouts/vue-layout.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
