/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck
/**
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import * as runtime from "@prisma/client/runtime/library";
import * as $Enums from "./enums.js";
import type * as Prisma from "./internal/prismaNamespace.js";

export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[];
  notIn?: string[];
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringFilter<$PrismaModel> | string;
};

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean;
};

export type EnumUserRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>;
  in?: $Enums.UserRole[];
  notIn?: $Enums.UserRole[];
  not?: Prisma.NestedEnumUserRoleFilter<$PrismaModel> | $Enums.UserRole;
};

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | null;
  notIn?: string[] | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null;
};

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[];
  notIn?: Date[] | string[];
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string;
};

export type JsonNullableFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<JsonNullableFilterBase<$PrismaModel>>,
        Exclude<keyof Required<JsonNullableFilterBase<$PrismaModel>>, "path">
      >,
      Required<JsonNullableFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<JsonNullableFilterBase<$PrismaModel>>, "path">>;

export type JsonNullableFilterBase<$PrismaModel = never> = {
  equals?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  path?: string;
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>;
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  not?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
};

export type BoolNullableFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null;
  not?: Prisma.NestedBoolNullableFilter<$PrismaModel> | boolean | null;
};

export type SortOrderInput = {
  sort: Prisma.SortOrder;
  nulls?: Prisma.NullsOrder;
};

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[];
  notIn?: string[];
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedStringFilter<$PrismaModel>;
  _max?: Prisma.NestedStringFilter<$PrismaModel>;
};

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedBoolFilter<$PrismaModel>;
  _max?: Prisma.NestedBoolFilter<$PrismaModel>;
};

export type EnumUserRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>;
  in?: $Enums.UserRole[];
  notIn?: $Enums.UserRole[];
  not?: Prisma.NestedEnumUserRoleWithAggregatesFilter<$PrismaModel> | $Enums.UserRole;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>;
};

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | null;
  notIn?: string[] | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>;
};

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[];
  notIn?: Date[] | string[];
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>;
};

export type JsonNullableWithAggregatesFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>,
        Exclude<keyof Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, "path">
      >,
      Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, "path">>;

export type JsonNullableWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  path?: string;
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>;
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  not?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedJsonNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedJsonNullableFilter<$PrismaModel>;
};

export type BoolNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null;
  not?: Prisma.NestedBoolNullableWithAggregatesFilter<$PrismaModel> | boolean | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedBoolNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedBoolNullableFilter<$PrismaModel>;
};

export type FloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  in?: number[];
  notIn?: number[];
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number;
};

export type EnumKycStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.KycStatus | Prisma.EnumKycStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.KycStatus[];
  notIn?: $Enums.KycStatus[];
  not?: Prisma.NestedEnumKycStatusFilter<$PrismaModel> | $Enums.KycStatus;
};

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?: Date[] | string[] | null;
  notIn?: Date[] | string[] | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null;
};

export type FloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  in?: number[];
  notIn?: number[];
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>;
  _min?: Prisma.NestedFloatFilter<$PrismaModel>;
  _max?: Prisma.NestedFloatFilter<$PrismaModel>;
};

export type EnumKycStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.KycStatus | Prisma.EnumKycStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.KycStatus[];
  notIn?: $Enums.KycStatus[];
  not?: Prisma.NestedEnumKycStatusWithAggregatesFilter<$PrismaModel> | $Enums.KycStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumKycStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumKycStatusFilter<$PrismaModel>;
};

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?: Date[] | string[] | null;
  notIn?: Date[] | string[] | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
};

export type JsonFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<JsonFilterBase<$PrismaModel>>,
        Exclude<keyof Required<JsonFilterBase<$PrismaModel>>, "path">
      >,
      Required<JsonFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<JsonFilterBase<$PrismaModel>>, "path">>;

export type JsonFilterBase<$PrismaModel = never> = {
  equals?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  path?: string;
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>;
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  not?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
};

export type JsonWithAggregatesFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<JsonWithAggregatesFilterBase<$PrismaModel>>,
        Exclude<keyof Required<JsonWithAggregatesFilterBase<$PrismaModel>>, "path">
      >,
      Required<JsonWithAggregatesFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<JsonWithAggregatesFilterBase<$PrismaModel>>, "path">>;

export type JsonWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  path?: string;
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>;
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  not?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedJsonFilter<$PrismaModel>;
  _max?: Prisma.NestedJsonFilter<$PrismaModel>;
};

export type EnumInvestmentStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.InvestmentStatus | Prisma.EnumInvestmentStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.InvestmentStatus[];
  notIn?: $Enums.InvestmentStatus[];
  not?: Prisma.NestedEnumInvestmentStatusFilter<$PrismaModel> | $Enums.InvestmentStatus;
};

export type FloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null;
  in?: number[] | null;
  notIn?: number[] | null;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null;
};

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[];
  notIn?: number[];
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntFilter<$PrismaModel> | number;
};

export type EnumInvestmentStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.InvestmentStatus | Prisma.EnumInvestmentStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.InvestmentStatus[];
  notIn?: $Enums.InvestmentStatus[];
  not?:
    | Prisma.NestedEnumInvestmentStatusWithAggregatesFilter<$PrismaModel>
    | $Enums.InvestmentStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumInvestmentStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumInvestmentStatusFilter<$PrismaModel>;
};

export type FloatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null;
  in?: number[] | null;
  notIn?: number[] | null;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatNullableWithAggregatesFilter<$PrismaModel> | number | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _sum?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
};

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[];
  notIn?: number[];
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
  _sum?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedIntFilter<$PrismaModel>;
  _max?: Prisma.NestedIntFilter<$PrismaModel>;
};

export type EnumProfitStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ProfitStatus | Prisma.EnumProfitStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.ProfitStatus[];
  notIn?: $Enums.ProfitStatus[];
  not?: Prisma.NestedEnumProfitStatusFilter<$PrismaModel> | $Enums.ProfitStatus;
};

export type EnumProfitStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ProfitStatus | Prisma.EnumProfitStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.ProfitStatus[];
  notIn?: $Enums.ProfitStatus[];
  not?: Prisma.NestedEnumProfitStatusWithAggregatesFilter<$PrismaModel> | $Enums.ProfitStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumProfitStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumProfitStatusFilter<$PrismaModel>;
};

export type EnumTransactionTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionType | Prisma.EnumTransactionTypeFieldRefInput<$PrismaModel>;
  in?: $Enums.TransactionType[];
  notIn?: $Enums.TransactionType[];
  not?: Prisma.NestedEnumTransactionTypeFilter<$PrismaModel> | $Enums.TransactionType;
};

export type EnumTransactionStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionStatus | Prisma.EnumTransactionStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.TransactionStatus[];
  notIn?: $Enums.TransactionStatus[];
  not?: Prisma.NestedEnumTransactionStatusFilter<$PrismaModel> | $Enums.TransactionStatus;
};

export type EnumTransactionTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionType | Prisma.EnumTransactionTypeFieldRefInput<$PrismaModel>;
  in?: $Enums.TransactionType[];
  notIn?: $Enums.TransactionType[];
  not?: Prisma.NestedEnumTransactionTypeWithAggregatesFilter<$PrismaModel> | $Enums.TransactionType;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTransactionTypeFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTransactionTypeFilter<$PrismaModel>;
};

export type EnumTransactionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionStatus | Prisma.EnumTransactionStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.TransactionStatus[];
  notIn?: $Enums.TransactionStatus[];
  not?:
    | Prisma.NestedEnumTransactionStatusWithAggregatesFilter<$PrismaModel>
    | $Enums.TransactionStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTransactionStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTransactionStatusFilter<$PrismaModel>;
};

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[];
  notIn?: string[];
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringFilter<$PrismaModel> | string;
};

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean;
};

export type NestedEnumUserRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>;
  in?: $Enums.UserRole[];
  notIn?: $Enums.UserRole[];
  not?: Prisma.NestedEnumUserRoleFilter<$PrismaModel> | $Enums.UserRole;
};

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | null;
  notIn?: string[] | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null;
};

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[];
  notIn?: Date[] | string[];
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string;
};

export type NestedBoolNullableFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null;
  not?: Prisma.NestedBoolNullableFilter<$PrismaModel> | boolean | null;
};

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[];
  notIn?: string[];
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedStringFilter<$PrismaModel>;
  _max?: Prisma.NestedStringFilter<$PrismaModel>;
};

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[];
  notIn?: number[];
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntFilter<$PrismaModel> | number;
};

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedBoolFilter<$PrismaModel>;
  _max?: Prisma.NestedBoolFilter<$PrismaModel>;
};

export type NestedEnumUserRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>;
  in?: $Enums.UserRole[];
  notIn?: $Enums.UserRole[];
  not?: Prisma.NestedEnumUserRoleWithAggregatesFilter<$PrismaModel> | $Enums.UserRole;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>;
};

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | null;
  notIn?: string[] | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>;
};

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null;
  in?: number[] | null;
  notIn?: number[] | null;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null;
};

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[];
  notIn?: Date[] | string[];
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>;
};

export type NestedJsonNullableFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<NestedJsonNullableFilterBase<$PrismaModel>>,
        Exclude<keyof Required<NestedJsonNullableFilterBase<$PrismaModel>>, "path">
      >,
      Required<NestedJsonNullableFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<NestedJsonNullableFilterBase<$PrismaModel>>, "path">>;

export type NestedJsonNullableFilterBase<$PrismaModel = never> = {
  equals?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  path?: string;
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>;
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  not?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
};

export type NestedBoolNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null;
  not?: Prisma.NestedBoolNullableWithAggregatesFilter<$PrismaModel> | boolean | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedBoolNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedBoolNullableFilter<$PrismaModel>;
};

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  in?: number[];
  notIn?: number[];
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number;
};

export type NestedEnumKycStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.KycStatus | Prisma.EnumKycStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.KycStatus[];
  notIn?: $Enums.KycStatus[];
  not?: Prisma.NestedEnumKycStatusFilter<$PrismaModel> | $Enums.KycStatus;
};

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?: Date[] | string[] | null;
  notIn?: Date[] | string[] | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null;
};

export type NestedFloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  in?: number[];
  notIn?: number[];
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>;
  _min?: Prisma.NestedFloatFilter<$PrismaModel>;
  _max?: Prisma.NestedFloatFilter<$PrismaModel>;
};

export type NestedEnumKycStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.KycStatus | Prisma.EnumKycStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.KycStatus[];
  notIn?: $Enums.KycStatus[];
  not?: Prisma.NestedEnumKycStatusWithAggregatesFilter<$PrismaModel> | $Enums.KycStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumKycStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumKycStatusFilter<$PrismaModel>;
};

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?: Date[] | string[] | null;
  notIn?: Date[] | string[] | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
};

export type NestedJsonFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<NestedJsonFilterBase<$PrismaModel>>,
        Exclude<keyof Required<NestedJsonFilterBase<$PrismaModel>>, "path">
      >,
      Required<NestedJsonFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<NestedJsonFilterBase<$PrismaModel>>, "path">>;

export type NestedJsonFilterBase<$PrismaModel = never> = {
  equals?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
  path?: string;
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>;
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null;
  not?:
    | runtime.InputJsonValue
    | Prisma.JsonFieldRefInput<$PrismaModel>
    | Prisma.JsonNullValueFilter;
};

export type NestedEnumInvestmentStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.InvestmentStatus | Prisma.EnumInvestmentStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.InvestmentStatus[];
  notIn?: $Enums.InvestmentStatus[];
  not?: Prisma.NestedEnumInvestmentStatusFilter<$PrismaModel> | $Enums.InvestmentStatus;
};

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null;
  in?: number[] | null;
  notIn?: number[] | null;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null;
};

export type NestedEnumInvestmentStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.InvestmentStatus | Prisma.EnumInvestmentStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.InvestmentStatus[];
  notIn?: $Enums.InvestmentStatus[];
  not?:
    | Prisma.NestedEnumInvestmentStatusWithAggregatesFilter<$PrismaModel>
    | $Enums.InvestmentStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumInvestmentStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumInvestmentStatusFilter<$PrismaModel>;
};

export type NestedFloatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null;
  in?: number[] | null;
  notIn?: number[] | null;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatNullableWithAggregatesFilter<$PrismaModel> | number | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _sum?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
};

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[];
  notIn?: number[];
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
  _sum?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedIntFilter<$PrismaModel>;
  _max?: Prisma.NestedIntFilter<$PrismaModel>;
};

export type NestedEnumProfitStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ProfitStatus | Prisma.EnumProfitStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.ProfitStatus[];
  notIn?: $Enums.ProfitStatus[];
  not?: Prisma.NestedEnumProfitStatusFilter<$PrismaModel> | $Enums.ProfitStatus;
};

export type NestedEnumProfitStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ProfitStatus | Prisma.EnumProfitStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.ProfitStatus[];
  notIn?: $Enums.ProfitStatus[];
  not?: Prisma.NestedEnumProfitStatusWithAggregatesFilter<$PrismaModel> | $Enums.ProfitStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumProfitStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumProfitStatusFilter<$PrismaModel>;
};

export type NestedEnumTransactionTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionType | Prisma.EnumTransactionTypeFieldRefInput<$PrismaModel>;
  in?: $Enums.TransactionType[];
  notIn?: $Enums.TransactionType[];
  not?: Prisma.NestedEnumTransactionTypeFilter<$PrismaModel> | $Enums.TransactionType;
};

export type NestedEnumTransactionStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionStatus | Prisma.EnumTransactionStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.TransactionStatus[];
  notIn?: $Enums.TransactionStatus[];
  not?: Prisma.NestedEnumTransactionStatusFilter<$PrismaModel> | $Enums.TransactionStatus;
};

export type NestedEnumTransactionTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionType | Prisma.EnumTransactionTypeFieldRefInput<$PrismaModel>;
  in?: $Enums.TransactionType[];
  notIn?: $Enums.TransactionType[];
  not?: Prisma.NestedEnumTransactionTypeWithAggregatesFilter<$PrismaModel> | $Enums.TransactionType;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTransactionTypeFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTransactionTypeFilter<$PrismaModel>;
};

export type NestedEnumTransactionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TransactionStatus | Prisma.EnumTransactionStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.TransactionStatus[];
  notIn?: $Enums.TransactionStatus[];
  not?:
    | Prisma.NestedEnumTransactionStatusWithAggregatesFilter<$PrismaModel>
    | $Enums.TransactionStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumTransactionStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumTransactionStatusFilter<$PrismaModel>;
};
