/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck
/**
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from "./models/User.js";
export type * from "./models/Account.js";
export type * from "./models/AccountGroup.js";
export type * from "./models/Token.js";
export type * from "./models/InvestmentPlan.js";
export type * from "./models/Investment.js";
export type * from "./models/Profit.js";
export type * from "./models/Transaction.js";
export type * from "./models/Currency.js";
export type * from "./models/Notification.js";
export type * from "./models/Faq.js";
export type * from "./models/Ban.js";
export type * from "./commonInputTypes.js";
