
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Account'
export type * from './models/AccountGroup'
export type * from './models/Token'
export type * from './models/InvestmentPlan'
export type * from './models/Investment'
export type * from './models/Profit'
export type * from './models/Transaction'
export type * from './models/Currency'
export type * from './models/Notification'
export type * from './models/Faq'
export type * from './models/Ban'
export type * from './commonInputTypes'