
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `UserTier` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserTier
 * 
 */
export type UserTierModel = runtime.Types.Result.DefaultSelection<Prisma.$UserTierPayload>

export type AggregateUserTier = {
  _count: UserTierCountAggregateOutputType | null
  _min: UserTierMinAggregateOutputType | null
  _max: UserTierMaxAggregateOutputType | null
}

export type UserTierMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserTierMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserTierCountAggregateOutputType = {
  id: number
  name: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UserTierMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type UserTierMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type UserTierCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UserTierAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserTier to aggregate.
   */
  where?: Prisma.UserTierWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserTiers to fetch.
   */
  orderBy?: Prisma.UserTierOrderByWithRelationInput | Prisma.UserTierOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserTierWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserTiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserTiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserTiers
  **/
  _count?: true | UserTierCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserTierMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserTierMaxAggregateInputType
}

export type GetUserTierAggregateType<T extends UserTierAggregateArgs> = {
      [P in keyof T & keyof AggregateUserTier]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserTier[P]>
    : Prisma.GetScalarType<T[P], AggregateUserTier[P]>
}




export type UserTierGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserTierWhereInput
  orderBy?: Prisma.UserTierOrderByWithAggregationInput | Prisma.UserTierOrderByWithAggregationInput[]
  by: Prisma.UserTierScalarFieldEnum[] | Prisma.UserTierScalarFieldEnum
  having?: Prisma.UserTierScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserTierCountAggregateInputType | true
  _min?: UserTierMinAggregateInputType
  _max?: UserTierMaxAggregateInputType
}

export type UserTierGroupByOutputType = {
  id: string
  name: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: UserTierCountAggregateOutputType | null
  _min: UserTierMinAggregateOutputType | null
  _max: UserTierMaxAggregateOutputType | null
}

type GetUserTierGroupByPayload<T extends UserTierGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserTierGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserTierGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserTierGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserTierGroupByOutputType[P]>
      }
    >
  > 



export type UserTierWhereInput = {
  AND?: Prisma.UserTierWhereInput | Prisma.UserTierWhereInput[]
  OR?: Prisma.UserTierWhereInput[]
  NOT?: Prisma.UserTierWhereInput | Prisma.UserTierWhereInput[]
  id?: Prisma.StringFilter<"UserTier"> | string
  name?: Prisma.StringFilter<"UserTier"> | string
  description?: Prisma.StringNullableFilter<"UserTier"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UserTier"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserTier"> | Date | string
  accounts?: Prisma.AccountListRelationFilter
  investmentPlans?: Prisma.InvestmentPlanListRelationFilter
}

export type UserTierOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  accounts?: Prisma.AccountOrderByRelationAggregateInput
  investmentPlans?: Prisma.InvestmentPlanOrderByRelationAggregateInput
}

export type UserTierWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.UserTierWhereInput | Prisma.UserTierWhereInput[]
  OR?: Prisma.UserTierWhereInput[]
  NOT?: Prisma.UserTierWhereInput | Prisma.UserTierWhereInput[]
  description?: Prisma.StringNullableFilter<"UserTier"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UserTier"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserTier"> | Date | string
  accounts?: Prisma.AccountListRelationFilter
  investmentPlans?: Prisma.InvestmentPlanListRelationFilter
}, "id" | "name">

export type UserTierOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserTierCountOrderByAggregateInput
  _max?: Prisma.UserTierMaxOrderByAggregateInput
  _min?: Prisma.UserTierMinOrderByAggregateInput
}

export type UserTierScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserTierScalarWhereWithAggregatesInput | Prisma.UserTierScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserTierScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserTierScalarWhereWithAggregatesInput | Prisma.UserTierScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserTier"> | string
  name?: Prisma.StringWithAggregatesFilter<"UserTier"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"UserTier"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserTier"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"UserTier"> | Date | string
}

export type UserTierCreateInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accounts?: Prisma.AccountCreateNestedManyWithoutTierInput
  investmentPlans?: Prisma.InvestmentPlanCreateNestedManyWithoutUserTiersInput
}

export type UserTierUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutTierInput
  investmentPlans?: Prisma.InvestmentPlanUncheckedCreateNestedManyWithoutUserTiersInput
}

export type UserTierUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accounts?: Prisma.AccountUpdateManyWithoutTierNestedInput
  investmentPlans?: Prisma.InvestmentPlanUpdateManyWithoutUserTiersNestedInput
}

export type UserTierUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutTierNestedInput
  investmentPlans?: Prisma.InvestmentPlanUncheckedUpdateManyWithoutUserTiersNestedInput
}

export type UserTierCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserTierUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserTierUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserTierCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserTierMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserTierMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserTierNullableScalarRelationFilter = {
  is?: Prisma.UserTierWhereInput | null
  isNot?: Prisma.UserTierWhereInput | null
}

export type UserTierListRelationFilter = {
  every?: Prisma.UserTierWhereInput
  some?: Prisma.UserTierWhereInput
  none?: Prisma.UserTierWhereInput
}

export type UserTierOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserTierCreateNestedOneWithoutAccountsInput = {
  create?: Prisma.XOR<Prisma.UserTierCreateWithoutAccountsInput, Prisma.UserTierUncheckedCreateWithoutAccountsInput>
  connectOrCreate?: Prisma.UserTierCreateOrConnectWithoutAccountsInput
  connect?: Prisma.UserTierWhereUniqueInput
}

export type UserTierUpdateOneWithoutAccountsNestedInput = {
  create?: Prisma.XOR<Prisma.UserTierCreateWithoutAccountsInput, Prisma.UserTierUncheckedCreateWithoutAccountsInput>
  connectOrCreate?: Prisma.UserTierCreateOrConnectWithoutAccountsInput
  upsert?: Prisma.UserTierUpsertWithoutAccountsInput
  disconnect?: Prisma.UserTierWhereInput | boolean
  delete?: Prisma.UserTierWhereInput | boolean
  connect?: Prisma.UserTierWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserTierUpdateToOneWithWhereWithoutAccountsInput, Prisma.UserTierUpdateWithoutAccountsInput>, Prisma.UserTierUncheckedUpdateWithoutAccountsInput>
}

export type UserTierCreateNestedManyWithoutInvestmentPlansInput = {
  create?: Prisma.XOR<Prisma.UserTierCreateWithoutInvestmentPlansInput, Prisma.UserTierUncheckedCreateWithoutInvestmentPlansInput> | Prisma.UserTierCreateWithoutInvestmentPlansInput[] | Prisma.UserTierUncheckedCreateWithoutInvestmentPlansInput[]
  connectOrCreate?: Prisma.UserTierCreateOrConnectWithoutInvestmentPlansInput | Prisma.UserTierCreateOrConnectWithoutInvestmentPlansInput[]
  connect?: Prisma.UserTierWhereUniqueInput | Prisma.UserTierWhereUniqueInput[]
}

export type UserTierUncheckedCreateNestedManyWithoutInvestmentPlansInput = {
  create?: Prisma.XOR<Prisma.UserTierCreateWithoutInvestmentPlansInput, Prisma.UserTierUncheckedCreateWithoutInvestmentPlansInput> | Prisma.UserTierCreateWithoutInvestmentPlansInput[] | Prisma.UserTierUncheckedCreateWithoutInvestmentPlansInput[]
  connectOrCreate?: Prisma.UserTierCreateOrConnectWithoutInvestmentPlansInput | Prisma.UserTierCreateOrConnectWithoutInvestmentPlansInput[]
  connect?: Prisma.UserTierWhereUniqueInput | Prisma.UserTierWhereUniqueInput[]
}

export type UserTierUpdateManyWithoutInvestmentPlansNestedInput = {
  create?: Prisma.XOR<Prisma.UserTierCreateWithoutInvestmentPlansInput, Prisma.UserTierUncheckedCreateWithoutInvestmentPlansInput> | Prisma.UserTierCreateWithoutInvestmentPlansInput[] | Prisma.UserTierUncheckedCreateWithoutInvestmentPlansInput[]
  connectOrCreate?: Prisma.UserTierCreateOrConnectWithoutInvestmentPlansInput | Prisma.UserTierCreateOrConnectWithoutInvestmentPlansInput[]
  upsert?: Prisma.UserTierUpsertWithWhereUniqueWithoutInvestmentPlansInput | Prisma.UserTierUpsertWithWhereUniqueWithoutInvestmentPlansInput[]
  set?: Prisma.UserTierWhereUniqueInput | Prisma.UserTierWhereUniqueInput[]
  disconnect?: Prisma.UserTierWhereUniqueInput | Prisma.UserTierWhereUniqueInput[]
  delete?: Prisma.UserTierWhereUniqueInput | Prisma.UserTierWhereUniqueInput[]
  connect?: Prisma.UserTierWhereUniqueInput | Prisma.UserTierWhereUniqueInput[]
  update?: Prisma.UserTierUpdateWithWhereUniqueWithoutInvestmentPlansInput | Prisma.UserTierUpdateWithWhereUniqueWithoutInvestmentPlansInput[]
  updateMany?: Prisma.UserTierUpdateManyWithWhereWithoutInvestmentPlansInput | Prisma.UserTierUpdateManyWithWhereWithoutInvestmentPlansInput[]
  deleteMany?: Prisma.UserTierScalarWhereInput | Prisma.UserTierScalarWhereInput[]
}

export type UserTierUncheckedUpdateManyWithoutInvestmentPlansNestedInput = {
  create?: Prisma.XOR<Prisma.UserTierCreateWithoutInvestmentPlansInput, Prisma.UserTierUncheckedCreateWithoutInvestmentPlansInput> | Prisma.UserTierCreateWithoutInvestmentPlansInput[] | Prisma.UserTierUncheckedCreateWithoutInvestmentPlansInput[]
  connectOrCreate?: Prisma.UserTierCreateOrConnectWithoutInvestmentPlansInput | Prisma.UserTierCreateOrConnectWithoutInvestmentPlansInput[]
  upsert?: Prisma.UserTierUpsertWithWhereUniqueWithoutInvestmentPlansInput | Prisma.UserTierUpsertWithWhereUniqueWithoutInvestmentPlansInput[]
  set?: Prisma.UserTierWhereUniqueInput | Prisma.UserTierWhereUniqueInput[]
  disconnect?: Prisma.UserTierWhereUniqueInput | Prisma.UserTierWhereUniqueInput[]
  delete?: Prisma.UserTierWhereUniqueInput | Prisma.UserTierWhereUniqueInput[]
  connect?: Prisma.UserTierWhereUniqueInput | Prisma.UserTierWhereUniqueInput[]
  update?: Prisma.UserTierUpdateWithWhereUniqueWithoutInvestmentPlansInput | Prisma.UserTierUpdateWithWhereUniqueWithoutInvestmentPlansInput[]
  updateMany?: Prisma.UserTierUpdateManyWithWhereWithoutInvestmentPlansInput | Prisma.UserTierUpdateManyWithWhereWithoutInvestmentPlansInput[]
  deleteMany?: Prisma.UserTierScalarWhereInput | Prisma.UserTierScalarWhereInput[]
}

export type UserTierCreateWithoutAccountsInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  investmentPlans?: Prisma.InvestmentPlanCreateNestedManyWithoutUserTiersInput
}

export type UserTierUncheckedCreateWithoutAccountsInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  investmentPlans?: Prisma.InvestmentPlanUncheckedCreateNestedManyWithoutUserTiersInput
}

export type UserTierCreateOrConnectWithoutAccountsInput = {
  where: Prisma.UserTierWhereUniqueInput
  create: Prisma.XOR<Prisma.UserTierCreateWithoutAccountsInput, Prisma.UserTierUncheckedCreateWithoutAccountsInput>
}

export type UserTierUpsertWithoutAccountsInput = {
  update: Prisma.XOR<Prisma.UserTierUpdateWithoutAccountsInput, Prisma.UserTierUncheckedUpdateWithoutAccountsInput>
  create: Prisma.XOR<Prisma.UserTierCreateWithoutAccountsInput, Prisma.UserTierUncheckedCreateWithoutAccountsInput>
  where?: Prisma.UserTierWhereInput
}

export type UserTierUpdateToOneWithWhereWithoutAccountsInput = {
  where?: Prisma.UserTierWhereInput
  data: Prisma.XOR<Prisma.UserTierUpdateWithoutAccountsInput, Prisma.UserTierUncheckedUpdateWithoutAccountsInput>
}

export type UserTierUpdateWithoutAccountsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  investmentPlans?: Prisma.InvestmentPlanUpdateManyWithoutUserTiersNestedInput
}

export type UserTierUncheckedUpdateWithoutAccountsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  investmentPlans?: Prisma.InvestmentPlanUncheckedUpdateManyWithoutUserTiersNestedInput
}

export type UserTierCreateWithoutInvestmentPlansInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accounts?: Prisma.AccountCreateNestedManyWithoutTierInput
}

export type UserTierUncheckedCreateWithoutInvestmentPlansInput = {
  id?: string
  name: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutTierInput
}

export type UserTierCreateOrConnectWithoutInvestmentPlansInput = {
  where: Prisma.UserTierWhereUniqueInput
  create: Prisma.XOR<Prisma.UserTierCreateWithoutInvestmentPlansInput, Prisma.UserTierUncheckedCreateWithoutInvestmentPlansInput>
}

export type UserTierUpsertWithWhereUniqueWithoutInvestmentPlansInput = {
  where: Prisma.UserTierWhereUniqueInput
  update: Prisma.XOR<Prisma.UserTierUpdateWithoutInvestmentPlansInput, Prisma.UserTierUncheckedUpdateWithoutInvestmentPlansInput>
  create: Prisma.XOR<Prisma.UserTierCreateWithoutInvestmentPlansInput, Prisma.UserTierUncheckedCreateWithoutInvestmentPlansInput>
}

export type UserTierUpdateWithWhereUniqueWithoutInvestmentPlansInput = {
  where: Prisma.UserTierWhereUniqueInput
  data: Prisma.XOR<Prisma.UserTierUpdateWithoutInvestmentPlansInput, Prisma.UserTierUncheckedUpdateWithoutInvestmentPlansInput>
}

export type UserTierUpdateManyWithWhereWithoutInvestmentPlansInput = {
  where: Prisma.UserTierScalarWhereInput
  data: Prisma.XOR<Prisma.UserTierUpdateManyMutationInput, Prisma.UserTierUncheckedUpdateManyWithoutInvestmentPlansInput>
}

export type UserTierScalarWhereInput = {
  AND?: Prisma.UserTierScalarWhereInput | Prisma.UserTierScalarWhereInput[]
  OR?: Prisma.UserTierScalarWhereInput[]
  NOT?: Prisma.UserTierScalarWhereInput | Prisma.UserTierScalarWhereInput[]
  id?: Prisma.StringFilter<"UserTier"> | string
  name?: Prisma.StringFilter<"UserTier"> | string
  description?: Prisma.StringNullableFilter<"UserTier"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UserTier"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserTier"> | Date | string
}

export type UserTierUpdateWithoutInvestmentPlansInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accounts?: Prisma.AccountUpdateManyWithoutTierNestedInput
}

export type UserTierUncheckedUpdateWithoutInvestmentPlansInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutTierNestedInput
}

export type UserTierUncheckedUpdateManyWithoutInvestmentPlansInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type UserTierCountOutputType
 */

export type UserTierCountOutputType = {
  accounts: number
  investmentPlans: number
}

export type UserTierCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accounts?: boolean | UserTierCountOutputTypeCountAccountsArgs
  investmentPlans?: boolean | UserTierCountOutputTypeCountInvestmentPlansArgs
}

/**
 * UserTierCountOutputType without action
 */
export type UserTierCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTierCountOutputType
   */
  select?: Prisma.UserTierCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserTierCountOutputType without action
 */
export type UserTierCountOutputTypeCountAccountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountWhereInput
}

/**
 * UserTierCountOutputType without action
 */
export type UserTierCountOutputTypeCountInvestmentPlansArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvestmentPlanWhereInput
}


export type UserTierSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  accounts?: boolean | Prisma.UserTier$accountsArgs<ExtArgs>
  investmentPlans?: boolean | Prisma.UserTier$investmentPlansArgs<ExtArgs>
  _count?: boolean | Prisma.UserTierCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userTier"]>

export type UserTierSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["userTier"]>

export type UserTierSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["userTier"]>

export type UserTierSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UserTierOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["userTier"]>
export type UserTierInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accounts?: boolean | Prisma.UserTier$accountsArgs<ExtArgs>
  investmentPlans?: boolean | Prisma.UserTier$investmentPlansArgs<ExtArgs>
  _count?: boolean | Prisma.UserTierCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserTierIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserTierIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserTierPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserTier"
  objects: {
    accounts: Prisma.$AccountPayload<ExtArgs>[]
    investmentPlans: Prisma.$InvestmentPlanPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["userTier"]>
  composites: {}
}

export type UserTierGetPayload<S extends boolean | null | undefined | UserTierDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserTierPayload, S>

export type UserTierCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserTierFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserTierCountAggregateInputType | true
  }

export interface UserTierDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserTier'], meta: { name: 'UserTier' } }
  /**
   * Find zero or one UserTier that matches the filter.
   * @param {UserTierFindUniqueArgs} args - Arguments to find a UserTier
   * @example
   * // Get one UserTier
   * const userTier = await prisma.userTier.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserTierFindUniqueArgs>(args: Prisma.SelectSubset<T, UserTierFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserTierClient<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserTier that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserTierFindUniqueOrThrowArgs} args - Arguments to find a UserTier
   * @example
   * // Get one UserTier
   * const userTier = await prisma.userTier.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserTierFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserTierFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserTierClient<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserTier that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTierFindFirstArgs} args - Arguments to find a UserTier
   * @example
   * // Get one UserTier
   * const userTier = await prisma.userTier.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserTierFindFirstArgs>(args?: Prisma.SelectSubset<T, UserTierFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserTierClient<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserTier that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTierFindFirstOrThrowArgs} args - Arguments to find a UserTier
   * @example
   * // Get one UserTier
   * const userTier = await prisma.userTier.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserTierFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserTierFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserTierClient<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserTiers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTierFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserTiers
   * const userTiers = await prisma.userTier.findMany()
   * 
   * // Get first 10 UserTiers
   * const userTiers = await prisma.userTier.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userTierWithIdOnly = await prisma.userTier.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserTierFindManyArgs>(args?: Prisma.SelectSubset<T, UserTierFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserTier.
   * @param {UserTierCreateArgs} args - Arguments to create a UserTier.
   * @example
   * // Create one UserTier
   * const UserTier = await prisma.userTier.create({
   *   data: {
   *     // ... data to create a UserTier
   *   }
   * })
   * 
   */
  create<T extends UserTierCreateArgs>(args: Prisma.SelectSubset<T, UserTierCreateArgs<ExtArgs>>): Prisma.Prisma__UserTierClient<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserTiers.
   * @param {UserTierCreateManyArgs} args - Arguments to create many UserTiers.
   * @example
   * // Create many UserTiers
   * const userTier = await prisma.userTier.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserTierCreateManyArgs>(args?: Prisma.SelectSubset<T, UserTierCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserTiers and returns the data saved in the database.
   * @param {UserTierCreateManyAndReturnArgs} args - Arguments to create many UserTiers.
   * @example
   * // Create many UserTiers
   * const userTier = await prisma.userTier.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserTiers and only return the `id`
   * const userTierWithIdOnly = await prisma.userTier.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserTierCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserTierCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserTier.
   * @param {UserTierDeleteArgs} args - Arguments to delete one UserTier.
   * @example
   * // Delete one UserTier
   * const UserTier = await prisma.userTier.delete({
   *   where: {
   *     // ... filter to delete one UserTier
   *   }
   * })
   * 
   */
  delete<T extends UserTierDeleteArgs>(args: Prisma.SelectSubset<T, UserTierDeleteArgs<ExtArgs>>): Prisma.Prisma__UserTierClient<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserTier.
   * @param {UserTierUpdateArgs} args - Arguments to update one UserTier.
   * @example
   * // Update one UserTier
   * const userTier = await prisma.userTier.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserTierUpdateArgs>(args: Prisma.SelectSubset<T, UserTierUpdateArgs<ExtArgs>>): Prisma.Prisma__UserTierClient<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserTiers.
   * @param {UserTierDeleteManyArgs} args - Arguments to filter UserTiers to delete.
   * @example
   * // Delete a few UserTiers
   * const { count } = await prisma.userTier.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserTierDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserTierDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserTiers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTierUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserTiers
   * const userTier = await prisma.userTier.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserTierUpdateManyArgs>(args: Prisma.SelectSubset<T, UserTierUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserTiers and returns the data updated in the database.
   * @param {UserTierUpdateManyAndReturnArgs} args - Arguments to update many UserTiers.
   * @example
   * // Update many UserTiers
   * const userTier = await prisma.userTier.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserTiers and only return the `id`
   * const userTierWithIdOnly = await prisma.userTier.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserTierUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserTierUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserTier.
   * @param {UserTierUpsertArgs} args - Arguments to update or create a UserTier.
   * @example
   * // Update or create a UserTier
   * const userTier = await prisma.userTier.upsert({
   *   create: {
   *     // ... data to create a UserTier
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserTier we want to update
   *   }
   * })
   */
  upsert<T extends UserTierUpsertArgs>(args: Prisma.SelectSubset<T, UserTierUpsertArgs<ExtArgs>>): Prisma.Prisma__UserTierClient<runtime.Types.Result.GetResult<Prisma.$UserTierPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserTiers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTierCountArgs} args - Arguments to filter UserTiers to count.
   * @example
   * // Count the number of UserTiers
   * const count = await prisma.userTier.count({
   *   where: {
   *     // ... the filter for the UserTiers we want to count
   *   }
   * })
  **/
  count<T extends UserTierCountArgs>(
    args?: Prisma.Subset<T, UserTierCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserTierCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserTier.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTierAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserTierAggregateArgs>(args: Prisma.Subset<T, UserTierAggregateArgs>): Prisma.PrismaPromise<GetUserTierAggregateType<T>>

  /**
   * Group by UserTier.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserTierGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserTierGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserTierGroupByArgs['orderBy'] }
      : { orderBy?: UserTierGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserTierGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserTierGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserTier model
 */
readonly fields: UserTierFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserTier.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserTierClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  accounts<T extends Prisma.UserTier$accountsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserTier$accountsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  investmentPlans<T extends Prisma.UserTier$investmentPlansArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserTier$investmentPlansArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvestmentPlanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserTier model
 */
export interface UserTierFieldRefs {
  readonly id: Prisma.FieldRef<"UserTier", 'String'>
  readonly name: Prisma.FieldRef<"UserTier", 'String'>
  readonly description: Prisma.FieldRef<"UserTier", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserTier", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"UserTier", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserTier findUnique
 */
export type UserTierFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTierInclude<ExtArgs> | null
  /**
   * Filter, which UserTier to fetch.
   */
  where: Prisma.UserTierWhereUniqueInput
}

/**
 * UserTier findUniqueOrThrow
 */
export type UserTierFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTierInclude<ExtArgs> | null
  /**
   * Filter, which UserTier to fetch.
   */
  where: Prisma.UserTierWhereUniqueInput
}

/**
 * UserTier findFirst
 */
export type UserTierFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTierInclude<ExtArgs> | null
  /**
   * Filter, which UserTier to fetch.
   */
  where?: Prisma.UserTierWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserTiers to fetch.
   */
  orderBy?: Prisma.UserTierOrderByWithRelationInput | Prisma.UserTierOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserTiers.
   */
  cursor?: Prisma.UserTierWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserTiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserTiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserTiers.
   */
  distinct?: Prisma.UserTierScalarFieldEnum | Prisma.UserTierScalarFieldEnum[]
}

/**
 * UserTier findFirstOrThrow
 */
export type UserTierFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTierInclude<ExtArgs> | null
  /**
   * Filter, which UserTier to fetch.
   */
  where?: Prisma.UserTierWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserTiers to fetch.
   */
  orderBy?: Prisma.UserTierOrderByWithRelationInput | Prisma.UserTierOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserTiers.
   */
  cursor?: Prisma.UserTierWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserTiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserTiers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserTiers.
   */
  distinct?: Prisma.UserTierScalarFieldEnum | Prisma.UserTierScalarFieldEnum[]
}

/**
 * UserTier findMany
 */
export type UserTierFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTierInclude<ExtArgs> | null
  /**
   * Filter, which UserTiers to fetch.
   */
  where?: Prisma.UserTierWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserTiers to fetch.
   */
  orderBy?: Prisma.UserTierOrderByWithRelationInput | Prisma.UserTierOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserTiers.
   */
  cursor?: Prisma.UserTierWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserTiers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserTiers.
   */
  skip?: number
  distinct?: Prisma.UserTierScalarFieldEnum | Prisma.UserTierScalarFieldEnum[]
}

/**
 * UserTier create
 */
export type UserTierCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTierInclude<ExtArgs> | null
  /**
   * The data needed to create a UserTier.
   */
  data: Prisma.XOR<Prisma.UserTierCreateInput, Prisma.UserTierUncheckedCreateInput>
}

/**
 * UserTier createMany
 */
export type UserTierCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserTiers.
   */
  data: Prisma.UserTierCreateManyInput | Prisma.UserTierCreateManyInput[]
}

/**
 * UserTier createManyAndReturn
 */
export type UserTierCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * The data used to create many UserTiers.
   */
  data: Prisma.UserTierCreateManyInput | Prisma.UserTierCreateManyInput[]
}

/**
 * UserTier update
 */
export type UserTierUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTierInclude<ExtArgs> | null
  /**
   * The data needed to update a UserTier.
   */
  data: Prisma.XOR<Prisma.UserTierUpdateInput, Prisma.UserTierUncheckedUpdateInput>
  /**
   * Choose, which UserTier to update.
   */
  where: Prisma.UserTierWhereUniqueInput
}

/**
 * UserTier updateMany
 */
export type UserTierUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserTiers.
   */
  data: Prisma.XOR<Prisma.UserTierUpdateManyMutationInput, Prisma.UserTierUncheckedUpdateManyInput>
  /**
   * Filter which UserTiers to update
   */
  where?: Prisma.UserTierWhereInput
  /**
   * Limit how many UserTiers to update.
   */
  limit?: number
}

/**
 * UserTier updateManyAndReturn
 */
export type UserTierUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * The data used to update UserTiers.
   */
  data: Prisma.XOR<Prisma.UserTierUpdateManyMutationInput, Prisma.UserTierUncheckedUpdateManyInput>
  /**
   * Filter which UserTiers to update
   */
  where?: Prisma.UserTierWhereInput
  /**
   * Limit how many UserTiers to update.
   */
  limit?: number
}

/**
 * UserTier upsert
 */
export type UserTierUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTierInclude<ExtArgs> | null
  /**
   * The filter to search for the UserTier to update in case it exists.
   */
  where: Prisma.UserTierWhereUniqueInput
  /**
   * In case the UserTier found by the `where` argument doesn't exist, create a new UserTier with this data.
   */
  create: Prisma.XOR<Prisma.UserTierCreateInput, Prisma.UserTierUncheckedCreateInput>
  /**
   * In case the UserTier was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserTierUpdateInput, Prisma.UserTierUncheckedUpdateInput>
}

/**
 * UserTier delete
 */
export type UserTierDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTierInclude<ExtArgs> | null
  /**
   * Filter which UserTier to delete.
   */
  where: Prisma.UserTierWhereUniqueInput
}

/**
 * UserTier deleteMany
 */
export type UserTierDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserTiers to delete
   */
  where?: Prisma.UserTierWhereInput
  /**
   * Limit how many UserTiers to delete.
   */
  limit?: number
}

/**
 * UserTier.accounts
 */
export type UserTier$accountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  where?: Prisma.AccountWhereInput
  orderBy?: Prisma.AccountOrderByWithRelationInput | Prisma.AccountOrderByWithRelationInput[]
  cursor?: Prisma.AccountWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AccountScalarFieldEnum | Prisma.AccountScalarFieldEnum[]
}

/**
 * UserTier.investmentPlans
 */
export type UserTier$investmentPlansArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvestmentPlan
   */
  select?: Prisma.InvestmentPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvestmentPlan
   */
  omit?: Prisma.InvestmentPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvestmentPlanInclude<ExtArgs> | null
  where?: Prisma.InvestmentPlanWhereInput
  orderBy?: Prisma.InvestmentPlanOrderByWithRelationInput | Prisma.InvestmentPlanOrderByWithRelationInput[]
  cursor?: Prisma.InvestmentPlanWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InvestmentPlanScalarFieldEnum | Prisma.InvestmentPlanScalarFieldEnum[]
}

/**
 * UserTier without action
 */
export type UserTierDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserTier
   */
  select?: Prisma.UserTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserTier
   */
  omit?: Prisma.UserTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserTierInclude<ExtArgs> | null
}
